# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # 버그 수정 (Patch Update)
  desc "Patch 업데이트"
  lane :patch do
    # Patch + 1
    increment_version_number(
      bump_type: "patch",
      xcodeproj: "RoomReviewer.xcodeproj"
    )
    
    increment_build_number(xcodeproj: "RoomReviewer.xcodeproj")
    build_app(scheme: "RoomReviewer")
    
    release_notes_text = File.read("release_notes.txt")

    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      release_notes: { "ko-KR" => release_notes_text }
    )
  end

  # 기능 추가 (Minor Update)
  desc "Minor 업데이트."
  lane :minor do
    # Minor + 1 & patch = 0
    increment_version_number(
      bump_type: "minor",
      xcodeproj: "RoomReviewer.xcodeproj"
    )

    increment_build_number(xcodeproj: "RoomReviewer.xcodeproj")
    build_app(scheme: "RoomReviewer")

    release_notes_text = File.read("release_notes.txt")

    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      release_notes: { "ko-KR" => release_notes_text }
    )
  end

  # 대규모 업데이트 (Major Update)
  desc "Major 업데이트"
  lane :major do
    # Major + 1 & minor, patch = 0
    increment_version_number(
      bump_type: "major",
      xcodeproj: "RoomReviewer.xcodeproj"
    )

    increment_build_number(xcodeproj: "RoomReviewer.xcodeproj")
    build_app(scheme: "RoomReviewer")

    release_notes_text = File.read("release_notes.txt")

    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      release_notes: { "ko-KR" => release_notes_text }
    )
  end

end


